name: Secreto

on:
  workflow_dispatch:

jobs:
  probando_secretos:
    name: Probar secretos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name Mi primer secreto
        run: echo ${{secrets.SONAR_TOKEN}}
